.TH MYSTRLEN 3 "September 2026" "libmyutils" "Library Functions"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.PP
.B int mystrlen(const char *s);
.SH DESCRIPTION
The
.B mystrlen
function calculates the number of characters in the string pointed to by
.I s
before the terminating null character.
.PP
The function returns the length of the string as an integer.
.SH AUTHOR
Muhammad Saad <msaaad8484@gmail.com>